Pract.04: Add 10-12 | Miroslav Stoyanovski
Justsvetoslavov/Introduction_to_programming pull request #102
Opened 2022-10-28 09:24 UTC by mir4oni3

Miroslav Stoyanovski
6 5MI0600195

2022-10-31 08:49 UTC, GeorgiTerziev02 requested changes

2022-10-31 08:49 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task10.cpp
> +	toBinary(n / 2);
Do it without recursion

2022-10-31 08:49 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task11.cpp
> +		if (a % i == 0 && b % i == 0) {
You can optimize it with the Euclidean algorithm

2022-10-31 08:49 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task11.cpp
> +		if (a % i == 0 && b % i == 0 && c % i == 0 && d % i == 0) {
Find gcd of the first two, then of third and fourth, then gcd of the results as you did in min of four numbers

2022-10-31 08:49 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task12.cpp
> +	while (!isPowerOfTwo(left)) {
Can be optimized. This way you will check every number if it is power of two.
Example you enter 333. You will check all the numbers from 333 to 256 if they are power of two and then all the numbers from 333 to 512. Which is not optimal

2022-10-31 08:49 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task12.cpp
> +	return right;
ternary operator

2022-11-03 14:52 UTC, Justsvetoslavov commented
Closing due to merged solutions.

2022-11-03 14:52 UTC, closed without merging