Prakt.04 : Add 09-11 | Stefka Lyaskalieva
Justsvetoslavov/Introduction_to_programming pull request #109
Opened 2022-10-29 16:17 UTC by stefka04

Stefka Lyaskalieva
2 4MI0600158

2022-10-30 07:43 UTC, GeorgiTerziev02 requested changes

2022-10-30 07:43 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task09.cpp
> +        case '%': return a % b; break;
What if b is equal to 0

2022-10-30 07:43 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task10.cpp
> +       binaryNum = binaryNum + (num % 2)*i;
You can use +=

2022-10-31 08:38 UTC, GeorgiTerziev02 requested changes

2022-10-31 08:38 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task09.cpp
> +        if (b == 0 && action == '/')
You are still not handling the case when the action is %

2022-11-03 14:54 UTC, Justsvetoslavov commented
Closing due to merged solutions.

2022-11-03 14:54 UTC, closed without merging