Pract.04: Add 14-15 | Georgi Stoychev
Justsvetoslavov/Introduction_to_programming pull request #124
Opened 2022-11-01 21:53 UTC by georgiStoychev17

Georgi Stoychev
2 7MI0600157

2022-11-02 07:35 UTC, plamena-ilieva requested changes

2022-11-02 07:35 UTC, plamena-ilieva commented on Tasks4/Tasks4/Task15.cpp
> +	return true;
Again, check numbers <= 1.

2022-11-02 07:35 UTC, plamena-ilieva commented on Tasks4/Tasks4/Task15.cpp
> +			std::cout << i << ".";
You print one additional '.' . Think about how you can skip it.

2022-11-03 14:52 UTC, Justsvetoslavov commented
Closing due to merged solutions.

2022-11-03 14:52 UTC, closed without merging