Doc Fix Pract 05 Array lesson
Justsvetoslavov/Introduction_to_programming pull request #133
Opened 2022-11-03 14:39 UTC by mir4oni3

-fixed array where element should be 44
-added missing ;

2022-11-03 14:46 UTC, Justsvetoslavov approved these changes
@mir4oni3 Could you add the changes for IS/Sem.05 as well ?

Thank you!

2022-11-03 19:00 UTC, GeorgiTerziev02 commented
What is the problem with the 44 in the array? Am I missing something?

2022-11-03 19:01 UTC, GeorgiTerziev02 commented on SI/Sem.05/README.md
> +int arr[] = {1, 2, 400, 44, 5}
Why?

2022-11-03 19:06 UTC, mir4oni3 commented
It was 4 before I fixed it, now it is 44.

On Thu, Nov 3, 2022, 21:00 Georgi Terziev ***@***.***> wrote:

> What is the problem with the 44 in the array? Am I missing something?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Justsvetoslavov/Introduction_to_programming/pull/133#issuecomment-1302544306>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3PKEENBHTUKOACEV3IJVUTWGQDWJANCNFSM6AAAAAARWGWR6U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-11-03 19:13 UTC, GeorgiTerziev02 requested changes
No need to change the 44, changing the value is on the next line. The point is that initialy on index 3 we have 4, the we change it to 44

2022-11-04 08:28 UTC, merged

2022-11-04 08:33 UTC, mir4oni3 commented
You are right! My bad.

On Thu, Nov 3, 2022, 21:13 Georgi Terziev ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> No need to change the 44, changing the value on the next line
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Justsvetoslavov/Introduction_to_programming/pull/133#pullrequestreview-1167532479>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3PKEENHCGDWRVUYFPBSJPTWGQFGDANCNFSM6AAAAAARWGWR6U>
> .
> You are receiving this because you were mentioned.Message ID:
> <Justsvetoslavov/Introduction_to_programming/pull/133/review/1167532479@
> github.com>
>