Prac05: Add 01-03 | Presiyana Borisova
Justsvetoslavov/Introduction_to_programming pull request #140
Opened 2022-11-05 09:40 UTC by PresiyanaBB

Presiyana Borisova
6 3MI0600240

2022-11-05 10:01 UTC, GeorgiTerziev02 requested changes

2022-11-05 10:01 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task02.cpp
> +					arr[j + 1] = temp;
Create a swap function to reuse some code

2022-11-05 10:13 UTC, Justsvetoslavov requested changes

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task01.cpp
> +    for (int i = 0; i < size; i++)
for (int i = 0; i < size - 1; i++)

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task01.cpp
> +        for (int j = 0; j < i; j++)
for (int j = i + 1; j < size; j++)

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task01.cpp
> +            if (arr[i] == copyArr[j])
arr[i] == arr[j]

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task03.cpp
> +void intToBinary(int num)
We need to return the number.

We convert it to binary and return it.

Revise this task.

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task01.cpp
> +    int copyArr[SIZE];
We do not need a copyArr.

We need to search in our given one without copies.

2022-11-05 10:13 UTC, Justsvetoslavov commented on SI/Sem.05/Pract.05/Task02.cpp
> +	int oddArr[SIZE];
That is correct.
However, as an initial solution it works (gotta point it out)

2022-11-12 11:07 UTC, merged

2022-11-12 11:07 UTC, plamena-ilieva commented
@Justsvetoslavov merging but please address the tasks.