Pract.05 | Add 04-10 | Nikola Svetoslavov
Justsvetoslavov/Introduction_to_programming pull request #144
Opened 2022-11-05 11:11 UTC by Justsvetoslavov

2022-11-05 12:45 UTC, GeorgiTerziev02 commented
Your pr is not following the rules. Please provide description! @Justsvetoslavov 🤡

2022-11-05 14:03 UTC, GeorgiTerziev02 requested changes

2022-11-06 12:13 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task04.cpp
> +    return ((num1 - num2) >= 0 ? (num1 - num2) : (num2 - num1));
True,

I tend to keep it due to different compilers.

2022-11-06 12:13 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task06.cpp
> +	return (S >= 'A' && S <= 'Z');
Will remove these.

2022-11-06 12:14 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task07.cpp
> +		if (isNumberInInterval(number,from,to)) {
VSCode does not respect it :(

2022-11-06 12:15 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task09.cpp
> +		case '%': return a % b;
Was thinking whether this check is not appropriate before passing to function.

However, I agree to add it.

2022-11-06 18:51 UTC, GeorgiTerziev02 approved these changes

2022-11-06 18:51 UTC, merged