Pract.05: Add 04-06 | Stefka Lyaskalieva
Justsvetoslavov/Introduction_to_programming pull request #149
Opened 2022-11-07 09:02 UTC by stefka04

Stefka Lyaskalieva
2 4MI0600158

2022-11-07 13:27 UTC, GeorgiTerziev02 requested changes
Good job. Change the function on task04 as in the comment I left.

2022-11-07 13:27 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task04.cpp
> +}
This should be function that accepts int[] and length

2022-11-07 13:27 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task05.cpp
> +}
Great

2022-11-11 21:04 UTC, Justsvetoslavov commented
Cherry-picked 5 & 6

2022-11-11 21:04 UTC, closed without merging