Pract.05: Add 07-09 | Miroslav Stoyanovski
Justsvetoslavov/Introduction_to_programming pull request #153
Opened 2022-11-08 15:41 UTC by mir4oni3

Miroslav Stoyanovski
6 5MI0600195

2022-11-10 19:45 UTC, GeorgiTerziev02 requested changes
Looks good, Good job! It would be great if you fix my comments. 👏 👏 👏

2022-11-10 19:45 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task09.cpp
> +			continue;
Check row or col < 0

2022-11-10 19:45 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task09.cpp
> +		}
create function

2022-11-10 19:45 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task09.cpp
> +			}
Duplicate code

2022-11-10 19:45 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task09.cpp
> +void print(char values[3][3]) {
Use these two cool lines to clear your console before every print
    std::cout << "\033[;H"; // Moves cursor to the top left
    std::cout << "\033[J"; // Clears the console

2022-11-10 19:45 UTC, GeorgiTerziev02 commented on SI/Sem.05/Pract.05/Task09.cpp
> +			values[row][col] = turn ? values[row][col] = 'X' : values[row][col] = 'O';
You are assigning the value two times here!

2022-11-12 10:58 UTC, Justsvetoslavov commented
Refactor the code and you can put a PR about tic-tac-toe as separate.

2022-11-12 10:58 UTC, closed without merging