Add files via upload
Justsvetoslavov/Introduction_to_programming pull request #17
Opened 2022-10-12 17:06 UTC by KrassimirTsvetanov

Красимир Цветанов - Група 2 - Практикум 2 - 9MI0600162

2022-10-13 17:49 UTC, dsvetoslavov approved these changes

2022-10-13 17:52 UTC, dsvetoslavov requested changes
Name the files TaskXX.cpp where XX is the number of the task e.g. Task01.cpp

2022-10-14 08:05 UTC, GeorgiTerziev02 approved these changes
Looks good

2022-10-14 08:10 UTC, GeorgiTerziev02 requested changes
Change file names

2022-10-19 15:02 UTC, closed without merging