Pract07str-08 | Mihaela Hadzhikovakeva
Justsvetoslavov/Introduction_to_programming pull request #186
Opened 2022-11-30 17:08 UTC by mihaela0911

Mihaela Hadzhikovakeva
6 6MI0600211

2022-12-04 16:43 UTC, dejansvetoslavov approved these changes

2022-12-04 16:43 UTC, dejansvetoslavov commented on SI/Sem.07/Pract.07/Strings/Task08.cpp
> +	int symbolsCount[SIZE_SYMBOLS] = {};
Is int needed here - it is a flag.

2022-12-04 16:43 UTC, dejansvetoslavov commented on SI/Sem.07/Pract.07/Strings/Task08.cpp
> +		{
It is a matter of style, but this looks odd - `for (int i = 0; i < MAX_SIZE && str[I] != '\0'; i++)` or maybe a while loop with a counter would look better

2022-12-04 16:43 UTC, dejansvetoslavov commented on SI/Sem.07/Pract.07/Strings/Task08.cpp
> +//void CountSymbols(char* symbols, int* symbolsCount)
You can remove the comments

2022-12-04 16:43 UTC, dejansvetoslavov commented
Awesome that you reworked the solution!! 🥇

2022-12-11 14:57 UTC, Justsvetoslavov requested changes
Waiting for the above comments to be addressed.

2022-12-16 16:14 UTC, Justsvetoslavov approved these changes

2022-12-16 16:15 UTC, merged