Pract.07: Add task 09 | Krasimir Ronkov
Justsvetoslavov/Introduction_to_programming pull request #195
Opened 2022-11-30 17:54 UTC by Krasimir-ronkov

2022-12-01 09:24 UTC, Justsvetoslavov commented
PR description is missing

2022-12-01 22:21 UTC, GeorgiTerziev02 approved these changes
You can have better names for your variables, also you can create some functions so that your code can be more readable

2022-12-01 22:21 UTC, GeorgiTerziev02 commented on SI/Sem.07/Pract.07/References/task09.cpp
> +    }
You can calculate pow in the while loop above, the for is not needed

2022-12-02 16:27 UTC, Justsvetoslavov requested changes
Address @GeorgiTerziev02 comment.
Remove the comments.
Move the code to appropriate functions.

2022-12-21 00:00 UTC, closed without merging