Pract.07: Add 01 | Polina Doncheva
Justsvetoslavov/Introduction_to_programming pull request #196
Opened 2022-11-30 17:59 UTC by polinaDoncheva

Polina Doncheva
6 9MI0600223

2022-12-01 20:44 UTC, GeorgiTerziev02 approved these changes

2022-12-01 20:44 UTC, GeorgiTerziev02 commented on SI/Sem.07/Pract.07/References/pract07zad2.cpp
> +	letter -= difference;
one line

2022-12-01 20:44 UTC, GeorgiTerziev02 commented on SI/Sem.07/Pract.07/References/pract07zad2.cpp
> +	letter += difference;
one line

2022-12-02 16:28 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/pract07.cpp
> +
Empty line 1 and 2.
Move the code 2 lines upwards.

2022-12-02 16:28 UTC, Justsvetoslavov requested changes
Remove unnecessary empty lines.
Address the comments.

2022-12-17 16:49 UTC, merged