Pract.07:  Add Task01-Task03 | Viktoria Koleva
Justsvetoslavov/Introduction_to_programming pull request #198
Opened 2022-11-30 22:44 UTC by Viktoria035

Viktoria Koleva
6 5MI0600139

2022-12-01 20:48 UTC, GeorgiTerziev02 requested changes

2022-12-01 20:48 UTC, GeorgiTerziev02 commented on SI/Sem.07/Pract.07/References/Task03.cpp
> +	}
Can be optimized
if a < b => swap
then if b < c => swap
then if a < b => swap

2022-12-01 20:48 UTC, GeorgiTerziev02 commented on SI/Sem.07/Pract.07/References/Task02.cpp
> +	}
You are doing the same check in the toUpperFunction
The same for the code below with the toLower
Upload only the two function - toUpper and toLower!

2022-12-02 20:14 UTC, Justsvetoslavov requested changes
When you address comments put appropriate commit messages.

2022-12-02 20:14 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/Task01.cpp
> +void swap(int* a, int* b)
why not references?

2022-12-02 20:14 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/Task02.cpp
> +const char UPPER_BORDER = 'Z';
this constants are not needed

2022-12-02 20:14 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/Task02.cpp
> +	if (a >= LOWER_BORDER_TO_SMALL && a <= LOWER_BORDER)
if-else is not needed.
Revise this solution.

2022-12-02 20:14 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/Task02.cpp
> +
if we are not in the if , what do we return?

2022-12-02 20:14 UTC, Justsvetoslavov commented on SI/Sem.07/Pract.07/References/Task03.cpp
> +
remove unnecessary empty lines.

2022-12-21 00:00 UTC, closed without merging