Pract. 07 (References): Add 07-09 | Georgi Baltiev
Justsvetoslavov/Introduction_to_programming pull request #201
Opened 2022-12-01 17:06 UTC by georgibaltiev

Georgi Baltiev
2 2MI0600168

2022-12-01 22:36 UTC, GeorgiTerziev02 requested changes

2022-12-01 22:36 UTC, GeorgiTerziev02 commented on Task07.cpp
> +    std::cout << hour << " " << minute << std::endl;
You do not check if hour is >= 24 when printing
Try the following input
4
19 15 120
20 20 25
18 25 230
21 10 3232

2022-12-01 22:36 UTC, GeorgiTerziev02 commented on Task07.cpp
> +    }
else if(.... && .....)

2022-12-04 12:18 UTC, GeorgiTerziev02 approved these changes

2022-12-06 15:53 UTC, Justsvetoslavov commented
@GeorgiTerziev02 @georgibaltiev Is it me or the task are not in the correct directory?

2022-12-10 18:05 UTC, Justsvetoslavov requested changes
Waiting for a reply on the above comment

2023-01-02 23:05 UTC, closed without merging