УП-практикум_12.10.22г.
Justsvetoslavov/Introduction_to_programming pull request #22
Opened 2022-10-15 05:45 UTC by kokopeevski

Калоян Кирилов Пеевски ( II група ) - факлутетен номер: 2MI0600170

2022-10-15 11:21 UTC, GeorgiTerziev02 requested changes
There are some mistakes and missed edge cases but overally looks good.

2022-10-15 11:21 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task9.cpp
> +	if (firstNum < secondNum && firstNum < thirdNum && secondNum < thirdNum)
This solution doesn't work for the input 5 6 5 and there is a much simpler solution with just reordering(swapping) the numbers with three ifs

2022-10-15 11:21 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task10.cpp
> +	if (res != 0) cout << "Result: " << res << endl;
This solution doesn't give output if your input is 5,+,-5 (the sum of 5 and -5 is zero)

2022-10-15 11:21 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task11.cpp
> +	if (a>=b && a>=c)
Your solution works but as similar to task 9 you can swap the numbers between them with three ifs and then print a*100 + b * 10 + c

2022-10-15 11:21 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task12.cpp
> +	if (month == 1 || month == 3 || month == 5 || month == 7 || month == 8 || month == 10 || month == 12)
The solution doesn't handle the case 31 12

2022-10-15 12:12 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/Task3.cpp
> +	(a > b) ? (cout << "The first one is bigger") : (cout << "The second one is bigger");
Should always avoid repetition.

2022-10-19 15:33 UTC, Justsvetoslavov commented
Review the new written PR rules and open new PRs if you would like (also check which ones are already merged ,as they will be duplicates).
[You can view them here](https://github.com/Justsvetoslavov/Introduction_to_programming)

2022-10-19 15:33 UTC, closed without merging