Georgi Stoychev 7MI0600157
Justsvetoslavov/Introduction_to_programming pull request #25
Opened 2022-10-16 15:30 UTC by georgiStoychev17

Georgi Stoychev 7MI0600157

2022-10-16 17:43 UTC, GeorgiTerziev02 requested changes
Check the comments and refactor.

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task1.cpp
> +	if ((yearNumber % 4 == 0) && (yearNumber % 400 == 0) || (yearNumber % 100 != 0)) {
Wrong if condition try 1901

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task10.cpp
> +	if (number2 != 0) {
The if condition number2 != 0 should be only in the '/' case

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task11.cpp
> +if (numberOne > numberTwo && numberTwo > numberThree) {
Think of an easier way to solve this task
Hint: swap the numbers between them

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task2.cpp
> +		case 'a': cout << "That is a part of the latin alphabet and also a vowel."; break;
You can reuse the cout logic like this
case 1:
case 2:
case 3: cout<<"....."
In each of the cases 1, 2, 3 we will execute the cout

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task2.cpp
> +			cout << "That is a part of the latin alphabet. ";
"This is consonant"

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task4.cpp
> +		cout << "Grade: " << 2;
You can put the 2 inside the string
"Grade: 2"

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task9.cpp
> +	if (numberOne > numberTwo && numberTwo > numberThree) {
Think of an easier way to solve this task
Hint: swap the numbers between them

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task12.cpp
> +	else if ((1 <= day < 31) && (1 <= month <= 12)) {
This solution does not cover all the cases try entering: 31 4 or 29 2

2022-10-16 17:43 UTC, GeorgiTerziev02 commented on SI/Sem.02/Tasks2/Task3.cpp
> +	int firstNumber, secondNumber, condition;
I am not sure what is all this logic for
The actual solution is much simple
Check this solution: https://github.com/Justsvetoslavov/Introduction_to_programming/pull/22/files#diff-fb15057d198d4557d8abfe0f9118fb3ba1bde4dcdcc0b5d457cc8bfcc1ae1816

2022-10-19 15:34 UTC, Justsvetoslavov commented
Review the new written PR rules and open new PRs if you would like (also check which ones are already merged ,as they will be duplicates).
[You can view them here](https://github.com/Justsvetoslavov/Introduction_to_programming)

2022-10-19 15:34 UTC, closed without merging