Практикум 2
Justsvetoslavov/Introduction_to_programming pull request #26
Opened 2022-10-16 16:11 UTC by thevlad0

Факултетен номер: 0MI0600204

2022-10-16 18:12 UTC, GeorgiTerziev02 requested changes
Looks good but there are small things that can be improved.
Good job for task 9 and task 11.

2022-10-16 18:12 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task7/Task7.cpp
> +        cout << "The big letter is " << (char)(letter - 32) << endl;
We actually have not learnt casting yet :), just increment/decrement the letter before the cout

2022-10-16 18:12 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task8/Task8.cpp
> +   for (size_t i = 0; i < num/10; i++)
The program should work only for ONE DIGIT numbers.
Also, check your case for the following input: 4.

2022-10-16 18:12 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task12/Task12.cpp
> +                    if(month == 12)
This check is useless here

2022-10-16 18:12 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/Task13/Task13.cpp
> +        a1 = (a/1000)*10 + ((a%1000)%100)%10;
Refactor line 19 and line 20, there is much simpler solution to the the digit
Line 19 just directly use %10 in the end

2022-10-19 15:33 UTC, Justsvetoslavov commented
Review the new written PR rules and open new PRs if you would like (also check which ones are already merged ,as they will be duplicates).
[You can view them here](https://github.com/Justsvetoslavov/Introduction_to_programming)

2022-10-19 15:33 UTC, closed without merging