Add files via upload
Justsvetoslavov/Introduction_to_programming pull request #32
Opened 2022-10-19 14:10 UTC by kmtoncheva

2022-10-19 15:29 UTC, Justsvetoslavov commented
Review the new written PR rules which you can view  [here](https://github.com/Justsvetoslavov/Introduction_to_programming).
Rename the files & open new PR/s. After that please include me or tag me for review.
If you are having any problems, ping me.

2022-10-21 07:20 UTC, GeorgiTerziev02 commented
For pract 02 the new rules for the PRs will not be considered. Do not close this pull request.

2022-10-21 14:32 UTC, Justsvetoslavov commented
@GeorgiTerziev02 We cannot cherry-pick due to single commits.
Do you still want to keep the PR ?

2022-10-22 10:25 UTC, GeorgiTerziev02 requested changes

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_1_p02.cpp
> +    if ((0 == year % 4 )||( 0 != year % 100 && 0 == year % 400) )
year % 4 == 0 is more readable way of writing code
Because you first write the expression and then you write what you expect to be equal to

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_4_p02.cpp
> +            std::cout << "Grade : 6 + ";
This should be an else if construction
With else if you will prevent making useless checks and
        if (result < 40) {
            std::cout << "Grade : 2";
        }
        if (result >= 40 && result < 60) {
            std::cout << "Grade : 3";
        }
and here you you won't have to write result >= 40 in the second if

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_6_p02.cpp
> +    if (D == 0)
else if

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_7_p02.cpp
> +    char UpperToLower = symbol + 32;
You should not do these operations in advance when you will need only one of them
You should do these operations when you enter the if for LowerToUpper
Also, use camelCase for naming you variables

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_8_p02.cpp
> +    int number = 0;
You don't need to intialize the variable with value, because you will overwrite it with the cin

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_9_p02.cpp
> +    if (a < b && a<c)
Think of a better way to do this task
Hint: swap the numbers between them if some condition is true

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_10_p02.cpp
> +    int SUM = a + b;
use camelCase for naming you variables

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_10_p02.cpp
> +    std::cin >> a;
The point of the task is to receive from the console a, b and character that is +,-,*,/ and based on the characted you should do a specific operation

2022-10-22 10:25 UTC, GeorgiTerziev02 commented on SI/Sem.02/Pract.02/task_11_p02.cpp
> +    if (a > b && a > c && a != 0)
Same problem and hint as in task 9

2022-10-22 10:28 UTC, GeorgiTerziev02 commented
Code review done. Think on the comments.
Closing PR because it is not meeting the new PR rules.

2022-10-22 10:28 UTC, closed without merging