Pract03: Add 04-05 | Presiyana Borisova
Justsvetoslavov/Introduction_to_programming pull request #43
Opened 2022-10-19 16:51 UTC by PresiyanaBB

Tasks 04 and 05 solution
Presiyana - 3MI0600240

2022-10-21 15:41 UTC, Justsvetoslavov requested changes

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task04.cpp
> +        if (i%n == 0)
if (i % n == 0)

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +    cin >> targetNumber;
targetNumber is between 0 and 100 , add a check.

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +    int counter = 0;
Suggestion: move the int counter = 0; just before the loop.

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +    } while (true);
We are looping until the numbers are equal.
Can we avoid/change the while (true) ?

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +
if (guessNumber < targetNumber)
				cout << "The number you are looking for is greater than your guess!\n";
 else if (guessNumber > targetNumber)
				cout << "The number you are looking for is less than your guess!\n";

2022-10-21 15:41 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +            cout << "You won with " << counter << " attempts";
Should be outside of the loop.
Our condition is in the while (<condition>)

2022-10-26 19:29 UTC, GeorgiTerziev02 commented
The correct solutions have already been uploaded
https://github.com/Justsvetoslavov/Introduction_to_programming/tree/master/SI/Sem.03/Pract.03

2022-10-26 19:29 UTC, closed without merging