Pract.03: Add 10-12 | Miroslav Stoyanovski
Justsvetoslavov/Introduction_to_programming pull request #51
Opened 2022-10-19 20:54 UTC by mir4oni3

Miroslav Stoyanovski
6 5MI0600195

2022-10-24 10:49 UTC, dejansvetoslavov requested changes

2022-10-24 10:49 UTC, dejansvetoslavov commented on SI/Sem.03/Pract.03/Task11.cpp
> +#include <iostream>
Is 0 Prime number?

2022-10-24 10:49 UTC, dejansvetoslavov commented on SI/Sem.03/Pract.03/Task10.cpp
> +		cout << n_copy << ", " << (n_copy+1);
Fix formatting. It is a bit hard to understand the code - try to refactor it in order to improve it.

2022-10-24 10:49 UTC, dejansvetoslavov commented on SI/Sem.03/Pract.03/Task12.cpp
> +
Remove blank line

2022-10-26 19:30 UTC, GeorgiTerziev02 commented
The correct solutions have already been uploaded
https://github.com/Justsvetoslavov/Introduction_to_programming/tree/master/SI/Sem.03/Pract.03

2022-10-26 19:30 UTC, closed without merging