Pract.02
Justsvetoslavov/Introduction_to_programming pull request #57
Opened 2022-10-21 06:52 UTC by Stanislava50

Tasks Prac2
Stanislava Zhelyazkova
4MI0600199

2022-10-21 07:18 UTC, GeorgiTerziev02 commented
For pract 02 the new rules for the PRs will not be considered. Do not close this pull request.

2022-10-21 14:53 UTC, Justsvetoslavov requested changes
Currently reviewed until task 8(included).
- Fix comments
- add spaces between operations as mentioned in some of the tasks.

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/Task01.cpp
> +// task01.cpp : This file contains the 'main' function. Program execution begins and ends there.
For the first 3 tasks you can see example solutions that are already merged.

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/Task02.cpp
> +	case'A':cout << "vowel";
You can check the solution that is in Pract.02/task02.cpp.
The problem here is we are repeating a lot of our code unnecessary.

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/Task03.cpp
> +	//�������� ��������, ����� ������ ��� �������� ����� � ����� ��� � �� ������.
You are having problems with the encoding you use on the comments.
Are you writing comments in Cyrillic?

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/task04.cpp
> +	else if (result<40)
Can our percentages be negative?
Shouldn't we cover this case?

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/task04.cpp
> +	else if(result>=70)
keep consistency and good practices.
Tabulations/Spaces between the operations and variables.
E.g: else if(result >= 70)

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/task06.cpp
> +	int a, b, c;
Re-visit this task.
- Shouldn't the discriminant be a separate variable?
- Do we always have roots?
- Do we always have a quadratic equation?

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/task08.cpp
> +    if (numeral == 1)
Re-write this task with a switch case.

2022-10-21 14:53 UTC, Justsvetoslavov commented on SI/Sem.02/Pract.02/task07.cpp
> +	if ('a' <= symbol <= 'z')
Re-visit this task.
- 'a' <= symbol <= 'z' does this work?
- if you have 2 conditions -> logical operator &&
- Check operator += and -=

2022-10-21 17:05 UTC, dejansvetoslavov requested changes

2022-10-21 17:05 UTC, dejansvetoslavov commented on SI/Sem.02/Pract.02/task10.cpp
> +//�������� ����� ����������, ����� �������� ���������� + , -, *, / �� ��� ������ �����.
We don't speak this language 😆

2022-10-21 17:05 UTC, dejansvetoslavov commented on SI/Sem.02/Pract.02/task10.cpp
> +    switch(sign)
Fix formatting.

2022-10-21 17:05 UTC, dejansvetoslavov commented on SI/Sem.02/Pract.02/task11.cpp
> +	if(a>b && a>>c && b>c)
This is wrong

2022-10-25 18:03 UTC, Justsvetoslavov commented
Adding label duplicate.
Closing PR due to single commit and unable to merge.

2022-10-25 18:03 UTC, closed without merging