Pract 03: Add 04-05 | Militsa Toncheva
Justsvetoslavov/Introduction_to_programming pull request #61
Opened 2022-10-21 11:17 UTC by milicavilica

Militsa Toncheva
Group 6 2MI0600216

2022-10-21 16:08 UTC, Justsvetoslavov requested changes

2022-10-21 16:08 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task04.cpp
> +		for (int i = 0; i < p; i++)
we can start from 1 and condition will change to <=.
In addition, p is not necessary.

2022-10-21 16:08 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task04.cpp
> +			cout << i + 1 << ' ';
From the above changes , we will swap the if and the result and remove the +1 on the i

2022-10-21 16:08 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +	if (num < 0 || num > 100)
Same as above.
Will return 1 and will have only the if statement.

2022-10-21 16:08 UTC, Justsvetoslavov commented on SI/Sem.03/Pract.03/Task05.cpp
> +		while (true)
Re-think to remove the while (true).
Hint: use do-while.

2022-10-26 19:30 UTC, GeorgiTerziev02 commented
The correct solutions have already been uploaded
https://github.com/Justsvetoslavov/Introduction_to_programming/tree/master/SI/Sem.03/Pract.03

2022-10-26 19:30 UTC, closed without merging