Pract.04: Add 01-03 | Momchil Uzunov
Justsvetoslavov/Introduction_to_programming pull request #79
Opened 2022-10-26 16:34 UTC by momouzunov2003

Momchil Uzunov
6 1MI0600146

2022-10-26 19:24 UTC, GeorgiTerziev02 requested changes
Some refactoring needed

2022-10-26 19:24 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 03.cpp
> +    if (num > 0)
num > 0 is a boolean expression, so it returns a boolean value that you can directly return

2022-10-26 19:24 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 03.cpp
> +    if (num < 0)
num > 0 is a boolean expression, so it returns a boolean value that you can directly return

2022-10-28 08:25 UTC, momouzunov2003 reviewed
Fixed Task03

2022-10-28 12:20 UTC, Justsvetoslavov approved these changes

2022-10-28 12:20 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task 03.cpp
> +   return (num>0);
return num > 0;

No brackets and spaces between variable & operations

2022-10-28 12:20 UTC, Justsvetoslavov commented on SI/Sem.04/Pract.04/Task 03.cpp
> +    return (num<0);
Same as IsPositive func comment.

2022-10-28 12:20 UTC, Justsvetoslavov commented
Closing due to merged solutions.
Address comments and contact us if you have questions.

2022-10-28 12:20 UTC, closed without merging