Pract.04: Add 01-03 | Danail Todorov
Justsvetoslavov/Introduction_to_programming pull request #81
Opened 2022-10-26 16:48 UTC by Danail3

Danail Todorov
6 0MI0600241

2022-10-26 19:27 UTC, GeorgiTerziev02 requested changes
Some refactoring needed

2022-10-26 19:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task01.cpp
> +int Sum(int a, int b)
Use camelCase for naming your functions

2022-10-26 19:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task02.cpp
> +	if (num % 2 == 0)
num % 2 is a boolean expression, so it returns a boolean value that you can directly return

2022-10-26 19:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +	if (num >= 0)
num >= 0 is a boolean expression, so it returns a boolean value that you can directly return

2022-10-26 19:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +	if (num < 0)
num < 0 is a boolean expression, so it returns a boolean value that you can directly return

2022-10-28 12:21 UTC, Justsvetoslavov commented
Closing due to merged solutions.
Address comments and contact us if you have questions.

2022-10-28 12:21 UTC, closed without merging