Pract.04: Add 04-06 | Momchil Uzunov
Justsvetoslavov/Introduction_to_programming pull request #86
Opened 2022-10-26 17:00 UTC by momouzunov2003

Momchil Uzunov
6 1MI0600146

2022-10-26 19:34 UTC, GeorgiTerziev02 requested changes
Some refactoring needed

2022-10-26 19:34 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 06.cpp
> +    if ((S >= 'A' && S <= 'Z') || (S>='a' && S<='z'))
(S >= 'A' && S <= 'Z') || (S>='a' && S<='z') is a boolean expression, so it returns a boolean value that you can directly return

2022-10-26 19:34 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 04.cpp
> +    {
You can use a ternary operator here

2022-10-28 08:40 UTC, momouzunov2003 commented
Updated tasks 04 and 06.

2022-10-31 08:33 UTC, GeorgiTerziev02 requested changes

2022-10-31 08:33 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 04.cpp
> +    return result;
No need of a variable here. You can directly return

2022-10-31 08:33 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 04.cpp
> +    return result;
Not working correctly. You are assigning a double to int so you are returning the int that will be converted to double

2022-10-31 08:33 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 06.cpp
> +    return (S >= 'A' && S <= 'Z');
No need of brackets

2022-10-31 08:33 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task 06.cpp
> +    return ((S >= 'A' && S <= 'Z') || (S >= 'a' && S <= 'z'));
No need of the first brackets

2022-11-05 09:41 UTC, closed without merging