Pract.04 task01 03
Justsvetoslavov/Introduction_to_programming pull request #88
Opened 2022-10-26 19:33 UTC by Viktoria035

Viktoria Koleva
6   5MI0600139

2022-10-26 22:27 UTC, GeorgiTerziev02 requested changes

2022-10-26 22:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task02.cpp
> +int isEven(int num)
Should return bool

2022-10-26 22:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +void isPositive(int numberP)
Should return bool

2022-10-26 22:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +	if (numberP >= 0)
zero is not positive

2022-10-26 22:27 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +void isNegative(int numberN)
should return bool

2022-10-28 12:22 UTC, Justsvetoslavov commented
Follow PR rules for PR title.

Closing due to merged solutions.
Address comments and contact us if you have questions.

2022-10-28 12:22 UTC, closed without merging