Pract.04: Add :01-03|Radina Ovcharova
Justsvetoslavov/Introduction_to_programming pull request #89
Opened 2022-10-26 20:42 UTC by radi676

Radina Ovcharova
6 3MI0600151

2022-10-26 22:22 UTC, GeorgiTerziev02 requested changes
Some refactoring needed. The functions in task2 and task3 should return bool

2022-10-26 22:22 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +void isNegative(int number) {
You should return bool

2022-10-26 22:22 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task03.cpp
> +void isPositive(int number) {
bool isPositive

2022-10-26 22:22 UTC, GeorgiTerziev02 commented on SI/Sem.04/Pract.04/Task02.cpp
> +int isEven(int num) {
bool isEven

2022-10-28 12:22 UTC, Justsvetoslavov commented
Closing due to merged solutions.
Address comments and contact us if you have questions.

2022-10-28 12:22 UTC, closed without merging